[package]
name = "goodmorning-bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = ["debug", "services-v1", "res-serde", "restrait", "req-serde"]
debug = []

res-serde = ["res-ser", "res-de"]
res-ser = ["serde-any"]
res-de = ["serde-any"]

req-serde = ["req-ser", "req-de"]
req-ser = ["serde-any"]
req-de = ["serde-any"]

serde-any = ["dep:serde"]

services-v1 = []

restrait = []
