[package]
name = "goodmorning-bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"]}

[features]
debug = []
serde = ["ser", "de"]
ser = ["serde-any"]
de = ["serde-any"]
serde-any = []

services-v1 = []

restrait = []
